# Generated by Django 3.1.7 on 2021-06-12 20:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode_of_payment', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CARD', 'Card Transfer'), ('CREDIT', 'Pay Later')], max_length=10)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Successful'), (2, 'Failed')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Payment transaction created date and time.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Payment transaction created date and time.')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ('-created_at',),
            },
        ),
    ]
