# Generated by Django 3.1.7 on 2021-07-18 13:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.TextField()),
                ('unit', models.CharField(choices=[('pc', 'pcs'), ('kg', 'kilograms'), ('lt', 'lt'), ('mt', 'mt')], default='pc', help_text='Measurement unit.', max_length=2)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Sold Item',
                'verbose_name_plural': 'Sold Items',
            },
        ),
    ]
