# Generated by Django 3.1.7 on 2021-07-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_solditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solditem',
            old_name='sale',
            new_name='payment',
        ),
    ]
