# Generated by Django 3.1.7 on 2021-06-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20210613_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='payments/receipts/'),
        ),
    ]
