# Generated by Django 3.1.7 on 2021-08-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_twilioservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoupload',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='shared'),
        ),
    ]
