# Generated by Django 3.2.7 on 2021-10-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210724_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Business Owner'), (2, 'Partner'), (3, 'Staff')], default=1),
        ),
    ]
