# Generated by Django 3.1.7 on 2021-05-14 10:57

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shared.utils.otp
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210513_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp', models.CharField(default=shared.utils.otp.generate_otp, help_text='A one-time password.', max_length=6, verbose_name='OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField(default=accounts.models.get_otp_expiration)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Code',
                'verbose_name_plural': 'Password Reset Codes',
                'ordering': ('-expire_at',),
            },
        ),
    ]
