# Generated by Django 3.1.7 on 2021-05-14 10:58

from django.db import migrations, models
import shared.utils.otp


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresetcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetcode',
            name='otp',
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='code',
            field=models.CharField(default=shared.utils.otp.generate_otp, help_text='A one-time password code.', max_length=6),
        ),
    ]
