# Generated by Django 3.1.7 on 2021-05-14 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210514_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetcode',
            old_name='code',
            new_name='otp',
        ),
    ]
