# Generated by Django 3.1.7 on 2021-05-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210515_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='font_size',
            field=models.PositiveSmallIntegerField(default=11, help_text='Font size in pixels.'),
        ),
        migrations.AddField(
            model_name='setting',
            name='terms_and_condition',
            field=models.BooleanField(default=False),
        ),
    ]
