# Generated by Django 3.1.7 on 2021-05-15 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210515_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='currency',
        ),
    ]
