# Generated by Django 3.1.7 on 2021-05-23 15:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0011_auto_20210520_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=100, verbose_name='product name')),
                ('unit', models.CharField(choices=[('pc', 'pcs'), ('hr', 'hours'), ('kg', 'kilograms'), ('lt', 'lt'), ('mt', 'mt')], help_text='Measurement unit.', max_length=2)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity left.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='business.businessaccount')),
            ],
            options={
                'verbose_name': 'Product Stock',
                'verbose_name_plural': 'Product Stocks',
            },
        ),
    ]
