# Generated by Django 3.1.7 on 2021-06-15 11:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=100, verbose_name='product name')),
                ('unit', models.CharField(choices=[('pc', 'pcs'), ('kg', 'kilograms'), ('lt', 'lt'), ('mt', 'mt')], help_text='Measurement unit.', max_length=2)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity left.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='business.businessaccount')),
            ],
            options={
                'verbose_name': 'Product Stock',
                'verbose_name_plural': 'Product Stocks',
            },
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity sold')),
                ('sales_date', models.DateField(auto_now=True, help_text='last sales date')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sold', to='inventory.stock')),
            ],
            options={
                'verbose_name': 'Product Sold',
                'verbose_name_plural': 'Products Sold',
            },
        ),
    ]
