# Generated by Django 3.1.7 on 2021-06-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.CharField(choices=[('pc', 'pcs'), ('kg', 'kilograms'), ('lt', 'lt'), ('mt', 'mt')], help_text='Measurement unit.', max_length=2),
        ),
    ]
