# Generated by Django 3.1.7 on 2021-06-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='sold',
            name='sold_at',
            field=models.DateTimeField(auto_now=True, help_text='last sales date'),
        ),
    ]
