# Generated by Django 3.2.7 on 2021-10-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210902_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('hg', 'hg'), ('dag', 'dag'), ('g', 'g'), ('dg', 'dg'), ('cg', 'cg'), ('mg', 'mg'), ('lb', 'lb'), ('in', 'in'), ('yd', 'yd'), ('mt', 'mt'), ('ft', 'ft'), ('ct', 'ct'), ('lt', 'lt'), ('cup', 'cup'), ('pt', 'pt'), ('gal', 'gal'), ('bbl', 'bbl'), ('pc', 'pc')], help_text='Measurement unit.', max_length=3),
        ),
    ]
