# Generated by Django 3.1.7 on 2021-06-11 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210611_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sold',
            old_name='sold_at',
            new_name='sales_date',
        ),
    ]
