# Generated by Django 3.2.7 on 2021-12-06 13:37

from django.db import migrations, models


def make_blank_barcodes_none(apps, schema_editor):
    Stock = apps.get_model('inventory', 'Stock')
    stocks = Stock.objects.filter(barcode_number='')
    for stock in stocks:
        stock.barcode_number = None
        stock.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_barcode_model'),
    ]

    operations = [
        migrations.RunPython(make_blank_barcodes_none),
        migrations.AlterField(
            model_name='stock',
            name='barcode_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
