# Generated by Django 3.2.7 on 2021-11-30 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_add_barcode_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_barcodes', to=settings.AUTH_USER_MODEL),
        ),
    ]
