# Generated by Django 3.2.7 on 2021-12-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20211212_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='product_photo',
        ),
    ]
