# Generated by Django 3.2.7 on 2021-12-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_barcode_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_restocked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
