# Generated by Django 3.2.7 on 2021-12-26 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_auto_20210808_1146'),
        ('inventory', '0011_stock_last_restocked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='product_photo',
            field=models.OneToOneField(blank=True, help_text='A foreign key to the Photo Upload object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_product_photo', to='shared.photoupload'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_photo', to='shared.photoupload'),
        ),
    ]
