# Generated by Django 3.1.7 on 2021-09-02 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20210724_2103'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('business_account', 'phone_number'), ('business_account', 'email')},
        ),
    ]
