# Generated by Django 3.1.7 on 2021-06-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profile_photo',
            new_name='photo',
        ),
    ]
