# Generated by Django 3.1.7 on 2021-05-17 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessCategory',
            new_name='BusinessType',
        ),
        migrations.AlterModelOptions(
            name='businesstype',
            options={'ordering': ('id', 'title'), 'verbose_name': 'Business Type', 'verbose_name_plural': 'Business Types'},
        ),
    ]
