# Generated by Django 3.1.7 on 2021-05-17 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20210517_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstype',
            name='description',
        ),
    ]
