# Generated by Django 3.1.7 on 2021-07-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20210715_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
