# Generated by Django 3.2.7 on 2021-11-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_businessaccounttax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessaccounttax',
            name='tax_identification_number',
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='tax_identification_number',
            field=models.CharField(blank=True, help_text='Unique TAX identification number issued by the government.', max_length=100, null=True),
        ),
    ]
