# Generated by Django 3.1.7 on 2021-05-17 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20210517_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessAccount',
        ),
    ]
