# Generated by Django 3.2.7 on 2021-11-23 08:26

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_add_tax_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='country',
            field=django_countries.fields.CountryField(default='NG', max_length=2),
        ),
    ]
