# Generated by Django 3.1.7 on 2021-05-19 22:57

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_businessaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
