# Generated by Django 3.2.7 on 2021-12-26 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_auto_20210808_1146'),
        ('business', '0006_alter_businessaccount_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_account', to='shared.photoupload'),
        ),
    ]
