# Generated by Django 3.1.7 on 2021-05-19 23:02

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20210519_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
