# Generated by Django 3.1.7 on 2021-05-20 18:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20210520_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='country',
            field=django_countries.fields.CountryField(default='NG', max_length=2),
        ),
    ]
