# Generated by Django 3.1.7 on 2021-06-04 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='custom_offer',
            new_name='custom_cost',
        ),
    ]
