# Generated by Django 3.1.7 on 2021-06-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mode_of_payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pay_later_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10),
        ),
    ]
