# Generated by Django 3.1.7 on 2021-06-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210604_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='custom_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='A total price offer for custom order.', max_digits=10, null=True),
        ),
    ]
