# Generated by Django 3.1.7 on 2021-06-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210607_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_later_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
