# Generated by Django 3.1.7 on 2021-06-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_pay_later_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('FROM_LIST', 'from list'), ('CUSTOM', 'custom order')], max_length=10),
        ),
    ]
