# Generated by Django 3.1.7 on 2021-06-09 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210608_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'default_related_name': 'order_items', 'ordering': ('updated_at',), 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='created_at',
        ),
    ]
