# Generated by Django 3.1.7 on 2021-06-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210609_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/receipts/'),
        ),
    ]
